# generated by ndk-pkg 0.1.35

get_filename_component(xz_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(xz_INCLUDE_DIR "${xz_INSTALL_DIR}/include")
set(xz_LIBRARY_DIR "${xz_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  xz::liblzma.a)
    add_library(xz::liblzma.a STATIC IMPORTED)
    set_target_properties(xz::liblzma.a PROPERTIES
        IMPORTED_LOCATION             "${xz_LIBRARY_DIR}/liblzma.a"
        INTERFACE_INCLUDE_DIRECTORIES "${xz_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  xz::liblzma.so)
    add_library(xz::liblzma.so STATIC IMPORTED)
    set_target_properties(xz::liblzma.so PROPERTIES
        IMPORTED_LOCATION             "${xz_LIBRARY_DIR}/liblzma.so"
        INTERFACE_INCLUDE_DIRECTORIES "${xz_INCLUDE_DIR}"
    )
endif()

set(xz_IMPORTED_TARGETS "xz::liblzma.a;xz::liblzma.so")
