# generated by ndk-pkg 0.1.35

get_filename_component(libjxl_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(libjxl_INCLUDE_DIR "${libjxl_INSTALL_DIR}/include")
set(libjxl_LIBRARY_DIR "${libjxl_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  libjxl::libjxl_threads.a)
    add_library(libjxl::libjxl_threads.a STATIC IMPORTED)
    set_target_properties(libjxl::libjxl_threads.a PROPERTIES
        IMPORTED_LOCATION             "${libjxl_LIBRARY_DIR}/libjxl_threads.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libjxl_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjxl::libjxl_threads.so)
    add_library(libjxl::libjxl_threads.so STATIC IMPORTED)
    set_target_properties(libjxl::libjxl_threads.so PROPERTIES
        IMPORTED_LOCATION             "${libjxl_LIBRARY_DIR}/libjxl_threads.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libjxl_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjxl::libhwy.a)
    add_library(libjxl::libhwy.a STATIC IMPORTED)
    set_target_properties(libjxl::libhwy.a PROPERTIES
        IMPORTED_LOCATION             "${libjxl_LIBRARY_DIR}/libhwy.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libjxl_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjxl::libhwy_contrib.a)
    add_library(libjxl::libhwy_contrib.a STATIC IMPORTED)
    set_target_properties(libjxl::libhwy_contrib.a PROPERTIES
        IMPORTED_LOCATION             "${libjxl_LIBRARY_DIR}/libhwy_contrib.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libjxl_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjxl::libjxl.a)
    add_library(libjxl::libjxl.a STATIC IMPORTED)
    set_target_properties(libjxl::libjxl.a PROPERTIES
        IMPORTED_LOCATION             "${libjxl_LIBRARY_DIR}/libjxl.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libjxl_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjxl::libjxl.so)
    add_library(libjxl::libjxl.so STATIC IMPORTED)
    set_target_properties(libjxl::libjxl.so PROPERTIES
        IMPORTED_LOCATION             "${libjxl_LIBRARY_DIR}/libjxl.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libjxl_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjxl::libjxl_dec.a)
    add_library(libjxl::libjxl_dec.a STATIC IMPORTED)
    set_target_properties(libjxl::libjxl_dec.a PROPERTIES
        IMPORTED_LOCATION             "${libjxl_LIBRARY_DIR}/libjxl_dec.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libjxl_INCLUDE_DIR}"
    )
endif()

set(libjxl_IMPORTED_TARGETS "libjxl::libjxl_threads.a;libjxl::libjxl_threads.so;libjxl::libhwy.a;libjxl::libhwy_contrib.a;libjxl::libjxl.a;libjxl::libjxl.so;libjxl::libjxl_dec.a")
