# generated by ndk-pkg 0.1.35

get_filename_component(libjpeg-turbo_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(libjpeg-turbo_INCLUDE_DIR "${libjpeg-turbo_INSTALL_DIR}/include")
set(libjpeg-turbo_LIBRARY_DIR "${libjpeg-turbo_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  libjpeg-turbo::libturbojpeg.so)
    add_library(libjpeg-turbo::libturbojpeg.so STATIC IMPORTED)
    set_target_properties(libjpeg-turbo::libturbojpeg.so PROPERTIES
        IMPORTED_LOCATION             "${libjpeg-turbo_LIBRARY_DIR}/libturbojpeg.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libjpeg-turbo_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjpeg-turbo::libturbojpeg.a)
    add_library(libjpeg-turbo::libturbojpeg.a STATIC IMPORTED)
    set_target_properties(libjpeg-turbo::libturbojpeg.a PROPERTIES
        IMPORTED_LOCATION             "${libjpeg-turbo_LIBRARY_DIR}/libturbojpeg.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libjpeg-turbo_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjpeg-turbo::libjpeg.so)
    add_library(libjpeg-turbo::libjpeg.so STATIC IMPORTED)
    set_target_properties(libjpeg-turbo::libjpeg.so PROPERTIES
        IMPORTED_LOCATION             "${libjpeg-turbo_LIBRARY_DIR}/libjpeg.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libjpeg-turbo_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libjpeg-turbo::libjpeg.a)
    add_library(libjpeg-turbo::libjpeg.a STATIC IMPORTED)
    set_target_properties(libjpeg-turbo::libjpeg.a PROPERTIES
        IMPORTED_LOCATION             "${libjpeg-turbo_LIBRARY_DIR}/libjpeg.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libjpeg-turbo_INCLUDE_DIR}"
    )
endif()

set(libjpeg-turbo_IMPORTED_TARGETS "libjpeg-turbo::libturbojpeg.so;libjpeg-turbo::libturbojpeg.a;libjpeg-turbo::libjpeg.so;libjpeg-turbo::libjpeg.a")
