# generated by ndk-pkg 0.1.35

get_filename_component(libpng_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(libpng_INCLUDE_DIR "${libpng_INSTALL_DIR}/include")
set(libpng_LIBRARY_DIR "${libpng_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  libpng::libpng16.a)
    add_library(libpng::libpng16.a STATIC IMPORTED)
    set_target_properties(libpng::libpng16.a PROPERTIES
        IMPORTED_LOCATION             "${libpng_LIBRARY_DIR}/libpng16.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libpng_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libpng::libpng.a)
    add_library(libpng::libpng.a STATIC IMPORTED)
    set_target_properties(libpng::libpng.a PROPERTIES
        IMPORTED_LOCATION             "${libpng_LIBRARY_DIR}/libpng.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libpng_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libpng::libpng.so)
    add_library(libpng::libpng.so STATIC IMPORTED)
    set_target_properties(libpng::libpng.so PROPERTIES
        IMPORTED_LOCATION             "${libpng_LIBRARY_DIR}/libpng.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libpng_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libpng::libpng16.so)
    add_library(libpng::libpng16.so STATIC IMPORTED)
    set_target_properties(libpng::libpng16.so PROPERTIES
        IMPORTED_LOCATION             "${libpng_LIBRARY_DIR}/libpng16.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libpng_INCLUDE_DIR}"
    )
endif()

set(libpng_IMPORTED_TARGETS "libpng::libpng16.a;libpng::libpng.a;libpng::libpng.so;libpng::libpng16.so")
