# generated by ndk-pkg 0.1.35

get_filename_component(libwebp_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(libwebp_INCLUDE_DIR "${libwebp_INSTALL_DIR}/include")
set(libwebp_LIBRARY_DIR "${libwebp_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  libwebp::libwebpmux.so)
    add_library(libwebp::libwebpmux.so STATIC IMPORTED)
    set_target_properties(libwebp::libwebpmux.so PROPERTIES
        IMPORTED_LOCATION             "${libwebp_LIBRARY_DIR}/libwebpmux.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libwebp_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libwebp::libwebpdecoder.so)
    add_library(libwebp::libwebpdecoder.so STATIC IMPORTED)
    set_target_properties(libwebp::libwebpdecoder.so PROPERTIES
        IMPORTED_LOCATION             "${libwebp_LIBRARY_DIR}/libwebpdecoder.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libwebp_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libwebp::libwebpdemux.so)
    add_library(libwebp::libwebpdemux.so STATIC IMPORTED)
    set_target_properties(libwebp::libwebpdemux.so PROPERTIES
        IMPORTED_LOCATION             "${libwebp_LIBRARY_DIR}/libwebpdemux.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libwebp_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libwebp::libwebp.so)
    add_library(libwebp::libwebp.so STATIC IMPORTED)
    set_target_properties(libwebp::libwebp.so PROPERTIES
        IMPORTED_LOCATION             "${libwebp_LIBRARY_DIR}/libwebp.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libwebp_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libwebp::libcpufeatures.a)
    add_library(libwebp::libcpufeatures.a STATIC IMPORTED)
    set_target_properties(libwebp::libcpufeatures.a PROPERTIES
        IMPORTED_LOCATION             "${libwebp_LIBRARY_DIR}/libcpufeatures.a"
        INTERFACE_INCLUDE_DIRECTORIES "${libwebp_INCLUDE_DIR}"
    )
endif()

set(libwebp_IMPORTED_TARGETS "libwebp::libwebpmux.so;libwebp::libwebpdecoder.so;libwebp::libwebpdemux.so;libwebp::libwebp.so;libwebp::libcpufeatures.a")
