# generated by ndk-pkg 0.1.35

get_filename_component(openexr_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(openexr_INCLUDE_DIR "${openexr_INSTALL_DIR}/include")
set(openexr_LIBRARY_DIR "${openexr_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  openexr::libOpenEXRUtil.so)
    add_library(openexr::libOpenEXRUtil.so STATIC IMPORTED)
    set_target_properties(openexr::libOpenEXRUtil.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libOpenEXRUtil.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libOpenEXRCore-3_1.so)
    add_library(openexr::libOpenEXRCore-3_1.so STATIC IMPORTED)
    set_target_properties(openexr::libOpenEXRCore-3_1.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libOpenEXRCore-3_1.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libOpenEXRCore.so)
    add_library(openexr::libOpenEXRCore.so STATIC IMPORTED)
    set_target_properties(openexr::libOpenEXRCore.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libOpenEXRCore.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libIex.so)
    add_library(openexr::libIex.so STATIC IMPORTED)
    set_target_properties(openexr::libIex.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libIex.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libOpenEXRUtil-3_1.so)
    add_library(openexr::libOpenEXRUtil-3_1.so STATIC IMPORTED)
    set_target_properties(openexr::libOpenEXRUtil-3_1.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libOpenEXRUtil-3_1.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libIlmThread.so)
    add_library(openexr::libIlmThread.so STATIC IMPORTED)
    set_target_properties(openexr::libIlmThread.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libIlmThread.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libIlmThread-3_1.so)
    add_library(openexr::libIlmThread-3_1.so STATIC IMPORTED)
    set_target_properties(openexr::libIlmThread-3_1.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libIlmThread-3_1.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libOpenEXR-3_1.so)
    add_library(openexr::libOpenEXR-3_1.so STATIC IMPORTED)
    set_target_properties(openexr::libOpenEXR-3_1.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libOpenEXR-3_1.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libOpenEXR.so)
    add_library(openexr::libOpenEXR.so STATIC IMPORTED)
    set_target_properties(openexr::libOpenEXR.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libOpenEXR.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  openexr::libIex-3_1.so)
    add_library(openexr::libIex-3_1.so STATIC IMPORTED)
    set_target_properties(openexr::libIex-3_1.so PROPERTIES
        IMPORTED_LOCATION             "${openexr_LIBRARY_DIR}/libIex-3_1.so"
        INTERFACE_INCLUDE_DIRECTORIES "${openexr_INCLUDE_DIR}"
    )
endif()

set(openexr_IMPORTED_TARGETS "openexr::libOpenEXRUtil.so;openexr::libOpenEXRCore-3_1.so;openexr::libOpenEXRCore.so;openexr::libIex.so;openexr::libOpenEXRUtil-3_1.so;openexr::libIlmThread.so;openexr::libIlmThread-3_1.so;openexr::libOpenEXR-3_1.so;openexr::libOpenEXR.so;openexr::libIex-3_1.so")
