# generated by ndk-pkg 0.1.35

get_filename_component(imath_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(imath_INCLUDE_DIR "${imath_INSTALL_DIR}/include")
set(imath_LIBRARY_DIR "${imath_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  imath::libImath.so)
    add_library(imath::libImath.so STATIC IMPORTED)
    set_target_properties(imath::libImath.so PROPERTIES
        IMPORTED_LOCATION             "${imath_LIBRARY_DIR}/libImath.so"
        INTERFACE_INCLUDE_DIRECTORIES "${imath_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  imath::libImath-3_1.so)
    add_library(imath::libImath-3_1.so STATIC IMPORTED)
    set_target_properties(imath::libImath-3_1.so PROPERTIES
        IMPORTED_LOCATION             "${imath_LIBRARY_DIR}/libImath-3_1.so"
        INTERFACE_INCLUDE_DIRECTORIES "${imath_INCLUDE_DIR}"
    )
endif()

set(imath_IMPORTED_TARGETS "imath::libImath.so;imath::libImath-3_1.so")
