# generated by ndk-pkg 0.1.35

get_filename_component(libtiff_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(libtiff_INCLUDE_DIR "${libtiff_INSTALL_DIR}/include")
set(libtiff_LIBRARY_DIR "${libtiff_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  libtiff::libtiffxx.so)
    add_library(libtiff::libtiffxx.so STATIC IMPORTED)
    set_target_properties(libtiff::libtiffxx.so PROPERTIES
        IMPORTED_LOCATION             "${libtiff_LIBRARY_DIR}/libtiffxx.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libtiff_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  libtiff::libtiff.so)
    add_library(libtiff::libtiff.so STATIC IMPORTED)
    set_target_properties(libtiff::libtiff.so PROPERTIES
        IMPORTED_LOCATION             "${libtiff_LIBRARY_DIR}/libtiff.so"
        INTERFACE_INCLUDE_DIRECTORIES "${libtiff_INCLUDE_DIR}"
    )
endif()

set(libtiff_IMPORTED_TARGETS "libtiff::libtiffxx.so;libtiff::libtiff.so")
