# generated by ndk-pkg 0.1.35

get_filename_component(zlib_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(zlib_INCLUDE_DIR "${zlib_INSTALL_DIR}/include")
set(zlib_LIBRARY_DIR "${zlib_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  zlib::libz.a)
    add_library(zlib::libz.a STATIC IMPORTED)
    set_target_properties(zlib::libz.a PROPERTIES
        IMPORTED_LOCATION             "${zlib_LIBRARY_DIR}/libz.a"
        INTERFACE_INCLUDE_DIRECTORIES "${zlib_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  zlib::libz.so)
    add_library(zlib::libz.so STATIC IMPORTED)
    set_target_properties(zlib::libz.so PROPERTIES
        IMPORTED_LOCATION             "${zlib_LIBRARY_DIR}/libz.so"
        INTERFACE_INCLUDE_DIRECTORIES "${zlib_INCLUDE_DIR}"
    )
endif()

set(zlib_IMPORTED_TARGETS "zlib::libz.a;zlib::libz.so")
