# generated by ndk-pkg 0.1.35

get_filename_component(giflib_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(giflib_INCLUDE_DIR "${giflib_INSTALL_DIR}/include")
set(giflib_LIBRARY_DIR "${giflib_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  giflib::libgif.a)
    add_library(giflib::libgif.a STATIC IMPORTED)
    set_target_properties(giflib::libgif.a PROPERTIES
        IMPORTED_LOCATION             "${giflib_LIBRARY_DIR}/libgif.a"
        INTERFACE_INCLUDE_DIRECTORIES "${giflib_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  giflib::libgif.so)
    add_library(giflib::libgif.so STATIC IMPORTED)
    set_target_properties(giflib::libgif.so PROPERTIES
        IMPORTED_LOCATION             "${giflib_LIBRARY_DIR}/libgif.so"
        INTERFACE_INCLUDE_DIRECTORIES "${giflib_INCLUDE_DIR}"
    )
endif()

set(giflib_IMPORTED_TARGETS "giflib::libgif.a;giflib::libgif.so")
