# generated by ndk-pkg 0.1.35

get_filename_component(brotli_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

set(brotli_INCLUDE_DIR "${brotli_INSTALL_DIR}/include")
set(brotli_LIBRARY_DIR "${brotli_INSTALL_DIR}/lib-no-versioning")


if (NOT TARGET  brotli::libbrotlidec-static.a)
    add_library(brotli::libbrotlidec-static.a STATIC IMPORTED)
    set_target_properties(brotli::libbrotlidec-static.a PROPERTIES
        IMPORTED_LOCATION             "${brotli_LIBRARY_DIR}/libbrotlidec-static.a"
        INTERFACE_INCLUDE_DIRECTORIES "${brotli_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  brotli::libbrotlicommon.so)
    add_library(brotli::libbrotlicommon.so STATIC IMPORTED)
    set_target_properties(brotli::libbrotlicommon.so PROPERTIES
        IMPORTED_LOCATION             "${brotli_LIBRARY_DIR}/libbrotlicommon.so"
        INTERFACE_INCLUDE_DIRECTORIES "${brotli_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  brotli::libbrotlidec.so)
    add_library(brotli::libbrotlidec.so STATIC IMPORTED)
    set_target_properties(brotli::libbrotlidec.so PROPERTIES
        IMPORTED_LOCATION             "${brotli_LIBRARY_DIR}/libbrotlidec.so"
        INTERFACE_INCLUDE_DIRECTORIES "${brotli_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  brotli::libbrotlienc-static.a)
    add_library(brotli::libbrotlienc-static.a STATIC IMPORTED)
    set_target_properties(brotli::libbrotlienc-static.a PROPERTIES
        IMPORTED_LOCATION             "${brotli_LIBRARY_DIR}/libbrotlienc-static.a"
        INTERFACE_INCLUDE_DIRECTORIES "${brotli_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  brotli::libbrotlicommon-static.a)
    add_library(brotli::libbrotlicommon-static.a STATIC IMPORTED)
    set_target_properties(brotli::libbrotlicommon-static.a PROPERTIES
        IMPORTED_LOCATION             "${brotli_LIBRARY_DIR}/libbrotlicommon-static.a"
        INTERFACE_INCLUDE_DIRECTORIES "${brotli_INCLUDE_DIR}"
    )
endif()

if (NOT TARGET  brotli::libbrotlienc.so)
    add_library(brotli::libbrotlienc.so STATIC IMPORTED)
    set_target_properties(brotli::libbrotlienc.so PROPERTIES
        IMPORTED_LOCATION             "${brotli_LIBRARY_DIR}/libbrotlienc.so"
        INTERFACE_INCLUDE_DIRECTORIES "${brotli_INCLUDE_DIR}"
    )
endif()

set(brotli_IMPORTED_TARGETS "brotli::libbrotlidec-static.a;brotli::libbrotlicommon.so;brotli::libbrotlidec.so;brotli::libbrotlienc-static.a;brotli::libbrotlicommon-static.a;brotli::libbrotlienc.so")
